[package]
name = "patchall"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
lalrpop-util = { version = "0.19.7", features = ["lexer"] }
once_cell = "1.10.0"
clap = { version = "4.0", features = ["derive"] }

[build-dependencies]
lalrpop = "0.19.7"

